worker_num: 0
TrainReader:
  sample_transforms:
  - Decode: {}
  - Resize3d: {target_size: [384, 1280], keep_ratio: False}
  - RandomFlip3d: { prob: 0.5 }
  - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
  - Permute: {}
  batch_size: 2
  shuffle: true
  drop_last: true
  collate_batch: ~
  use_shared_memory: false

EvalReader:
  sample_transforms:
      - Decode: {}
      - Resize3d: {target_size: [384, 1280], keep_ratio: False}
      - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
      - Permute: {}
  batch_size: 1
  shuffle: false
  drop_last: false
  drop_empty: false
  collate_batch: ~

TestReader:
  sample_transforms:
      - Decode: {}
      - Resize3d: {target_size: [384, 1280], keep_ratio: False}
      - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
      - Permute: {}
  batch_size: 1
  shuffle: false
  drop_last: false
