_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  './_base_/a_ppyolov2_p_reader.yml',
]

log_iter: 100
snapshot_epoch: 8
weights: output/c_yolo_r50vd_atss_ota_minicoco/model_final
find_unused_parameters: True

epoch: 180

LearningRate:
  base_lr: 0.005
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones:
    - 120
  - !LinearWarmup
    start_factor: 0.
    steps: 1000

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0005
    type: L2


architecture: YOLOv3
pretrain_weights: https://paddledet.bj.bcebos.com/models/pretrained/ResNet50_vd_ssld_pretrained.pdparams
norm_type: sync_bn
use_ema: true
ema_decay: 0.9998

YOLOv3:
  backbone: ResNet
  neck: PPYOLOPAN
  yolo_head: YOLOXHeadv3
  post_process: ~

ResNet:
  depth: 50
  variant: d
  return_idx: [1, 2, 3]
  freeze_at: -1
  freeze_norm: false

PPYOLOPAN:
  drop_block: true
  block_size: 3
  keep_prob: 0.9
  spp: true

YOLOXHeadv3:
  fpn_strides: [32, 16, 8]
  grid_cell_scale: 5
  grid_cell_offset: 0.5
  loss_weight: {obj: 1.0, class: 1.0, bbox: 1.0, iou: 5.0}
  static_assigner_epoch: 60
  ignore_obj: False
  static_assigner:
    name: ATSSAssigner
    topk: 15
    force_gt_matching: False
  assigner:
    name: SimOTAAssigner
    topk: 10
    alpha: 1.0
    beta: 3.0
    force_gt_matching: False
  nms:
    name: MultiClassNMS
    nms_top_k: 1000
    keep_top_k: 100
    score_threshold: 0.05
    nms_threshold: 0.6
