_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/optimizer_60e.yml',
  '_base_/ppdetr_r50vd.yml',
  '_base_/ppdetr_reader.yml',
]

weights: output/ppdetr_r50vd_60e_coco/model_final
find_unused_parameters: True
log_iter: 200
