_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  './_base_/optimizer_30e.yml',
  './_base_/ppyoloe_vit_reader.yml',
]

log_iter: 200
snapshot_epoch: 2
weights: output/ppyoloe_vitdet_one_30e/model_final

architecture: ViTDet
#norm_type: sync_bn
use_ema: true
ema_decay: 0.9999
ema_decay_type: "exponential"
ema_black_list: ['pos_embed', 'proj_conv']
custom_black_list: ['reduce_mean']
use_fused_allreduce_gradients: &use_checkpoint False


ViTDet:
  backbone: VisionTransformer
  neck: ~
  head: PPYOLOTHead


VisionTransformer:
  patch_size: 16
  embed_dim: 768
  depth: 12
  num_heads: 12
  mlp_ratio: 4
  qkv_bias: True
  drop_rate: 0.0
  drop_path_rate: 0.2
  init_values: 0.1
  final_norm: False
  use_rel_pos_bias: False
  use_sincos_pos_emb: True
  epsilon: 0.000001 # 1e-6
  out_indices: [11, ]
  with_fpn: True
  out_with_norm: False
  use_checkpoint: *use_checkpoint
  pretrained: https://bj.bcebos.com/v1/paddledet/models/pretrained/vit_base_cae_pretrained.pdparams


PPYOLOTHead:
  in_channels: 768
  fpn_strides: [16]
  use_varifocal_loss: True
  loss_weight: {class: 1.0, iou: 2.5, l1: 0.25}
  assigner:
    name: TaskAlignedAssigner
    topk: 9
    alpha: 1.0
    beta: 6.0
  nms:
    name: MultiClassNMS
    nms_top_k: 1000
    keep_top_k: 300
    score_threshold: 0.01
    nms_threshold: 0.7
