_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  './_base_/optimizer_300e.yml',
  './_base_/yolox_reader.yml'
]

log_iter: 100
snapshot_epoch: 10
weights: output/yolox_m_300e_coco/model_final
find_unused_parameters: True

architecture: YOLOX
norm_type: sync_bn
use_ema: True
ema_decay: 0.9999
ema_decay_type: "exponential"
depth_mult: 0.67
width_mult: 0.75

YOLOX:
  backbone: CSPDarkNet
  neck: YOLOCSPPAN
  head: YOLOXHead
  size_range: [15, 25]

CSPDarkNet:
  arch: "X"
  return_idx: [2, 3, 4]

YOLOCSPPAN:
  depthwise: False

YOLOXHead:
  l1_epoch: 285
  loss_weight: {class: 1.0, obj: 1.0, iou: 5.0, l1: 1.0}
  assigner:
    name: SimOTAAssigner
    candidate_topk: 10
    use_vfl: False
  nms:
    name: MultiClassNMS
    nms_top_k: 1000
    keep_top_k: 100
    score_threshold: 0.001
    nms_threshold: 0.65
