_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  './_base_/optimizer_36e.yml',
  './_base_/crn_reader.yml'
]

log_iter: 100
snapshot_epoch: 2
weights: output/yolox_crn_s_36e_coco/model_final
find_unused_parameters: True
pretrain_weights: https://paddledet.bj.bcebos.com/models/pretrained/CSPResNetb_s_pretrained.pdparams

architecture: YOLOX
use_ema: True
ema_decay: 0.9998
ema_decay_type: "exponential"
depth_mult: 0.33
width_mult: 0.50

YOLOX:
  backbone: CSPResNet
  neck: YOLOCSPPAN
  head: YOLOXHead
  size_range: [15, 25]

CSPResNet:
  layers: [3, 6, 6, 3]
  channels: [64, 128, 256, 512, 1024]
  return_idx: [1, 2, 3]
  use_large_stem: True

YOLOCSPPAN:
  depthwise: False

YOLOXHead:
  l1_epoch: 34
  loss_weight: {class: 1.0, obj: 1.0, iou: 5.0, l1: 1.0}
  assigner:
    name: SimOTAAssigner
    candidate_topk: 10
    use_vfl: False
  nms:
    name: MultiClassNMS
    nms_top_k: 1000
    keep_top_k: 100
    score_threshold: 0.001
    nms_threshold: 0.65
