_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/optimizer_1x.yml',
  '_base_/dino_vit_mae.yml',
  '_base_/dino_640_reader.yml',
]

weights: output/dino_vit_mae_1x_coco/model_final
find_unused_parameters: True
log_iter: 100
