_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  './_base_/e_yolo_cd53.yml',
  './_base_/e_yolo_reader.yml',
]

log_iter: 100
snapshot_epoch: 8
weights: output/e_yolo_cd53_atss_minicoco/model_final
find_unused_parameters: True

epoch: 180

LearningRate:
  base_lr: 0.01
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones:
    - 120
  - !LinearWarmup
    start_factor: 0.
    steps: 1000

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0005
    type: L2
