epoch: 50

LearningRate:
  base_lr: 0.0001
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones: [44, 48]
    use_warmup: false

OptimizerBuilder:
  clip_grad_by_norm: 0.01
  regularizer: false
  optimizer:
    type: AdamW
    weight_decay: 0.05
