_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/gfl_r50vd_pan.yml',
  '_base_/optimizer_2x.yml',
  '_base_/gfl_reader_ms.yml',
]

weights: output/gfl_r50vd_pan_v2_ms_2x_coco/model_final
find_unused_parameters: True
log_iter: 100
snapshot_epoch: 2

GFL:
  backbone: ResNet
  neck: PPYOLOPANv2
  head: GFLHead

PPYOLOPANv2:
  out_channel: 256
  num_extra_levels: 2
  drop_block: true
