_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/gfl_r50_fpn.yml',
  '_base_/optimizer_1x.yml',
  '_base_/gfl_reader.yml',
]

weights: output/gfl_r50vd_bifpn_1x_coco/model_final
find_unused_parameters: True
pretrain_weights: https://paddledet.bj.bcebos.com/models/pretrained/ResNet50_vd_ssld_pretrained.pdparams
log_iter: 100
snapshot_epoch: 2

GFL:
  backbone: ResNet
  neck: BiFPN
  head: GFLHead

ResNet:
  depth: 50
  variant: d
  norm_type: bn
  freeze_at: 0
  return_idx: [1, 2, 3]
  num_stages: 4

BiFPN:
  out_channel: 256
  num_extra_levels: 2
