worker_num: 4
eval_height: &eval_height 640
eval_width: &eval_width 640
eval_size: &eval_size [*eval_height, *eval_width]

TrainReader:
  sample_transforms:
    - Decode: {}
    - Mosaic:
        prob: 1.0
        input_dim: [ 640, 640 ]
        degrees: [ -10, 10 ]
        scale: [ 0.1, 2.0 ]
        shear: [ -2, 2 ]
        translate: [ -0.1, 0.1 ]
        enable_mixup: True
        mixup_prob: 1.0
        mixup_scale: [ 0.5, 1.5 ]
    - AugmentHSV: { is_bgr: False, hgain: 5, sgain: 30, vgain: 30 }
    - PadResize: { target_size: 640 }
    - RandomFlip: {}
  batch_transforms:
    - BatchRandomResize: {target_size: [320, 352, 384, 416, 448, 480, 512, 544, 576, 608, 640, 672, 704, 736, 768], random_size: True, random_interp: True, keep_ratio: False}
    - Permute: {}
    - PadGT: {}
  batch_size: 8
  shuffle: true
  drop_last: true
  use_shared_memory: false
  collate_batch: true
  mosaic_epoch: 285

EvalReader:
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: *eval_size, keep_ratio: True, interp: 1}
    - Pad: {size: *eval_size, fill_value: [114., 114., 114.]}
    - Permute: {}
  batch_size: 2

TestReader:
  inputs_def:
    image_shape: [3, *eval_height, *eval_width]
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: *eval_size, keep_ratio: True, interp: 1}
    - Pad: {size: *eval_size, fill_value: [114., 114., 114.]}
    - Permute: {}
  batch_size: 1
