worker_num: 2
TrainReader:
  sample_transforms:
  - Decode: {}
  - RandomFlip: {prob: 0.5}
  - TRMosaic:
      prob: 0.8
      target_size: [ 640, 640 ]
      translate: [ -0.1, 0.1 ]
      scale: [ 0.1, 2.0 ]
      degree: [ -10, 10 ]
      shear: [ -2, 2 ]
      fill_value: [ 123.675, 116.28, 103.53 ]
  - RandomDistort: {}
  - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
  - Pad: {size: [640, 640], fill_value: [0., 0., 0.]}
  - NormalizeBox: {}
  - BboxXYXY2XYWH: {}
  - Permute: {}
  batch_size: 2
  shuffle: true
  drop_last: true
  collate_batch: false
  use_shared_memory: false
  mosaic_epoch: 550


EvalReader:
  sample_transforms:
  - Decode: {}
  - Resize: {target_size: [640, 640], keep_ratio: True}
  - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
  - Pad: {size: [640, 640], fill_value: [0., 0., 0.]}
  - Permute: {}
  batch_size: 1
  shuffle: false
  drop_last: false


TestReader:
  sample_transforms:
  - Decode: {}
  - Resize: {target_size: [640, 640], keep_ratio: True}
  - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
  - Pad: {size: [640, 640], fill_value: [0., 0., 0.]}
  - Permute: {}
  batch_size: 1
  shuffle: false
  drop_last: false
